/*
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.analisearquivo.tela;

import java.io.File;

import javax.swing.JFileChooser;

import com.analisearquivo.classes.Analise;
import com.analisearquivo.classes.ComparaArquivo;

/**
 *
 * @author prince
 */
public class jAnalise extends javax.swing.JFrame {

    /**
     * Creates new form jAnalise
     */
	
	private Analise file1, file2;
	
    public jAnalise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtArq2 = new javax.swing.JTextField();
        txtArq1 = new javax.swing.JTextField();
        btnAbrirArq1 = new javax.swing.JButton();
        btnAbrirArq2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbDir1 = new javax.swing.JLabel();
        lbTam1 = new javax.swing.JLabel();
        lbDt1 = new javax.swing.JLabel();
        chLer1 = new javax.swing.JCheckBox();
        chEscrever1 = new javax.swing.JCheckBox();
        chExecutar1 = new javax.swing.JCheckBox();
        chLer2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chEscrever2 = new javax.swing.JCheckBox();
        chExecutar2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbDir2 = new javax.swing.JLabel();
        lbTam2 = new javax.swing.JLabel();
        lbDt2 = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbInfo1 = new javax.swing.JLabel();
        lbInfo2 = new javax.swing.JLabel();
        lbInfo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAbrirArq1.setText("Abrir arquivo 1");
        btnAbrirArq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArq1ActionPerformed(evt);
            }
        });

        btnAbrirArq2.setText("Abrir arquivo 2");
        btnAbrirArq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArq2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Analise de Arquivos");

        jLabel2.setText("Diretório");

        jLabel6.setText("Tamanho");

        jLabel7.setText("Data de modificação");

        lbDir1.setText("N/A");

        lbTam1.setText("N/A");

        lbDt1.setText("N/A");

        chLer1.setText("Ler");
        chLer1.setEnabled(false);

        chEscrever1.setText("Escrever");
        chEscrever1.setEnabled(false);

        chExecutar1.setText("Executar");
        chExecutar1.setEnabled(false);

        chLer2.setText("Ler");
        chLer2.setEnabled(false);

        jLabel3.setText("Diretório");

        chEscrever2.setText("Escrever");
        chEscrever2.setEnabled(false);

        chExecutar2.setText("Executar");
        chExecutar2.setEnabled(false);

        jLabel8.setText("Tamanho");

        jLabel9.setText("Data de modificação");

        lbDir2.setText("N/A");

        lbTam2.setText("N/A");

        lbDt2.setText("N/A");

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnCompararActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbInfo1.setText("N/A");

        lbInfo2.setText("N/A");

        lbInfo3.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrirArq2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArq2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDir2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chLer2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chEscrever2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chExecutar2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDt2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTam2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbrirArq1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArq1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDt1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTam1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDir1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chLer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chEscrever1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chExecutar1)))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComparar)
                    .addComponent(lbInfo1)
                    .addComponent(lbInfo2)
                    .addComponent(lbInfo3))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnComparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInfo1)
                        .addGap(27, 27, 27)
                        .addComponent(lbInfo2)
                        .addGap(29, 29, 29)
                        .addComponent(lbInfo3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtArq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAbrirArq1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lbDir1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chLer1)
                                .addComponent(chEscrever1)
                                .addComponent(chExecutar1))
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(lbTam1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(lbDt1))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAbrirArq2)
                                .addComponent(txtArq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(lbDir2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chLer2)
                                .addComponent(chEscrever2)
                                .addComponent(chExecutar2))
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(lbTam2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(lbDt2)))
                        .addComponent(jSeparator1)))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArq1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(null, null);
        
        File file = jFileChooser.getSelectedFile();
        
        if(file.exists()){
        	this.file1 = new Analise(file.getParent()+"\\"+file.getName());
        	lbDir1.setText(file1.getDiretorio());
        	lbDt1.setText(file1.getDataModificacao());
        	lbTam1.setText(String.valueOf(file1.getTamanho())+" Bytes");
        	chEscrever1.setSelected(file1.isEscrever());
        	chLer1.setSelected(file1.isLer());
        	chExecutar1.setSelected(file1.isExecutar());
        }
        
        txtArq1.setText(file.getParent()+"\\"+file.getName());
        
    }//GEN-LAST:event_btnAbrirArq1ActionPerformed

    private void btnAbrirArq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArq2ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(null, null);
        
        File file = jFileChooser.getSelectedFile();
        
        if(file.exists()){
        	this.file2 = new Analise(file.getParent()+"\\"+file.getName());
        	lbDir2.setText(file2.getDiretorio());
        	lbDt2.setText(file2.getDataModificacao());
        	lbTam2.setText(String.valueOf(file2.getTamanho())+" Bytes");
        	chEscrever2.setSelected(file2.isEscrever());
        	chLer2.setSelected(file2.isLer());
        	chExecutar2.setSelected(file2.isExecutar());
        }
        
        txtArq2.setText(file.getParent()+"\\"+file.getName());
    }//GEN-LAST:event_btnAbrirArq2ActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	try{
    		ComparaArquivo c = new ComparaArquivo(this.file1, this.file2);
    		lbInfo1.setText(c.getComparaGeral());
    		lbInfo2.setText(c.getComparaTamanhos());
    		lbInfo3.setText(c.getComparaDatas());
    	}catch(Exception e){
    		lbInfo1.setText("É necessário que seja selecionado os 2 arquivos para comparação!");
    	}
    	
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jAnalise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArq1;
    private javax.swing.JButton btnAbrirArq2;
    private javax.swing.JButton btnComparar;
    private javax.swing.JCheckBox chEscrever1;
    private javax.swing.JCheckBox chEscrever2;
    private javax.swing.JCheckBox chExecutar1;
    private javax.swing.JCheckBox chExecutar2;
    private javax.swing.JCheckBox chLer1;
    private javax.swing.JCheckBox chLer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDir1;
    private javax.swing.JLabel lbDir2;
    private javax.swing.JLabel lbDt1;
    private javax.swing.JLabel lbDt2;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbInfo2;
    private javax.swing.JLabel lbInfo3;
    private javax.swing.JLabel lbTam1;
    private javax.swing.JLabel lbTam2;
    private javax.swing.JTextField txtArq1;
    private javax.swing.JTextField txtArq2;
    // End of variables declaration//GEN-END:variables
}
